swagger: "2.0"

info:
  title: URL Shortener API
  description: Submit URLs and get unique code
  version: 1.0.0

host: https://<api-id>.execute-api.<region>.amazonaws.com

basePath: /v1
schemes:
  - https

paths:
  /urls/{code}:
    get:
      summary: Returns original URL by providing code
      parameters:
        - in: path
          name: code
          schema:
            type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          message: https://this-is-the-original-url.com

  /urls:
    post:
      summary: Returns unique code after submiting URL
      requestBody:
        required: true
        content:
          schema:
            type: object
            properties:
              url:
                type: string
      produces:
        - application/json
      responses:
        200:
          message: https://short-url.com
